services:
  - type: web
    name: urb-civ-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: urb-civ-frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://urb-civ-backend.onrender.com 