services:
  - type: web
    name: chatbot-gobierno-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://chatbot-gobierno.vercel.app 